# 2. Convolution and Pooling (10 - 10 pts)

### a) Write a function for convolution operation in the cell below. Write your own code with your own algorithm. It should have necessary error checks for matrix dimensions (consider multichannel matrices). Inputs must have the same structure as Tensorflow convolution operation and also the results must be same. Check [tf.nn.convolution](https://www.tensorflow.org/api_docs/python/tf/nn/convolution)

In [2]:
import tensorflow as tf
import numpy as np

In [54]:
def my_convolution(my_input, my_filter, my_padding, my_strides):
    # WRITE YOUR OWN CONVOLUTION IMPLEMENTATION HERE
    if(my_padding is "VALID"):
        conv_input = my_input
        my_output = np.zeros((conv_input.shape[0], conv_input.shape[1] - int(my_filter.shape[0] - 1), 
                            conv_input.shape[2] - int(my_filter.shape[1] - 1), my_filter.shape[3]))
        for batch in range(conv_input.shape[0]):
            for channel in range(my_filter.shape[3]):
                for i in range(my_output.shape[1]):
                    for j in range(my_output.shape[2]):
                        my_output[batch, i, j, channel] = np.sum(conv_input[batch, i:i+my_filter.shape[0], 
                                                                     j:j+my_filter.shape[1], :]*my_filter[:,:,:,channel])
            
    elif(my_padding is "SAME"):
        pad_1, pad_2 = int(my_filter.shape[0]/2), int(my_filter.shape[1]/2)
        conv_input = np.zeros((my_input.shape[0], my_input.shape[1] + 2*pad_1, 
                               my_input.shape[2] + 2*pad_2, my_input.shape[3]))
        conv_input[:,pad_1:-pad_1, pad_2:-pad_2, :] = my_input
        my_output = np.zeros((conv_input.shape[0], conv_input.shape[1] - int(my_filter.shape[0]/2 + 1), 
                            conv_input.shape[2] - int(my_filter.shape[1]/2 + 1), my_filter.shape[3]))
        for batch in range(my_input.shape[0]):
            for channel in range(my_filter.shape[3]):
                for i in range(my_output.shape[1]):
                    for j in range(my_output.shape[2]):
                        my_output[batch, i, j, channel] = np.sum(conv_input[batch, pad_1+i:pad_1+i+my_filter.shape[0], 
                                                                     pad_2+j:pad_2+j+my_filter.shape[1], :]*my_filter[:,:,:,channel])
        
    
    return my_output

In [55]:
def tf_convolution(tf_input, tf_filter, tf_padding, tf_strides):
    
    sess = tf.Session()
    tf_function = tf.nn.convolution(input=tf_input, filter=tf_filter, padding=tf_padding, strides=tf_strides)
    tf_output = sess.run(tf_function)
    sess.close()
    
    return tf_output

In [56]:
sample_input = np.random.random([1,4,4,1])
sample_filter = np.random.random([2,2,1,1])
sample_padding = "SAME"
sample_strides = [1,1]

tf_output = tf_convolution(sample_input,sample_filter,sample_padding,sample_strides)
my_output = my_convolution(sample_input,sample_filter,sample_padding,sample_strides)

print("input:")
print(sample_input)
print("filter:")
print(sample_filter)
print("output:")
print(tf_output)
print("my output:")
print(my_output)

input:
[[[[0.8849542 ]
   [0.80155565]
   [0.53770348]
   [0.49037045]]

  [[0.19978963]
   [0.3222855 ]
   [0.20571725]
   [0.29153332]]

  [[0.05587875]
   [0.88019014]
   [0.08306128]
   [0.57875444]]

  [[0.53963681]
   [0.30117825]
   [0.44686997]
   [0.84025394]]]]
filter:
[[[[0.31608263]]

  [[0.19951109]]]


 [[[0.83815882]]

  [[0.51743322]]]]
output:
[[[[0.77385456]
   [0.737207  ]
   [0.59106582]
   [0.39934881]]

  [[0.62972445]
   [0.92362952]
   [0.4922731 ]
   [0.57723676]]

  [[0.80141098]
   [0.77844504]
   [0.95104546]
   [0.88720048]]

  [[0.23065822]
   [0.18435273]
   [0.30888782]
   [0.26558968]]]]
my output:
[[[[0.77385456]
   [0.737207  ]
   [0.59106582]
   [0.39934881]]

  [[0.62972445]
   [0.92362952]
   [0.4922731 ]
   [0.57723676]]

  [[0.80141098]
   [0.77844504]
   [0.95104546]
   [0.88720048]]

  [[0.23065822]
   [0.18435273]
   [0.30888782]
   [0.26558968]]]]


### b) Write a function for pooling operation in the cell below. Write your own code with your own algorithm. It should have necessary error checks for matrix dimensions (consider multichannel matrices). Inputs must have the same structure as Tensorflow pooling operation and also the results must be same. Check [tf.nn.pool](https://www.tensorflow.org/api_docs/python/tf/nn/pool)

In [70]:
def my_pooling(my_input, my_window_shape, my_pooling_type, my_padding, my_strides):
    # WRITE YOUR OWN POOLING IMPLEMENTATION HERE
    my_output = np.zeros((my_input.shape[0], 
                           int((my_input.shape[1] - my_window_shape[0])/my_strides[0] + 1),
                           int((my_input.shape[2] - my_window_shape[1])/my_strides[1] + 1),
                           my_input.shape[3]))
     
    for batch in range(my_input.shape[0]):
        for channel in range(my_filter.shape[3]):
            for i in range(my_output.shape[1]):
                for j in range(my_output.shape[2]):
                    my_output[batch, i, j, channel] = np.max(my_input[batch, i:i+my_filter.shape[0]])

    
    return my_output

In [71]:
def tf_pooling(tf_input, tf_window_shape, tf_pooling_type, tf_padding, tf_strides):
    
    sess = tf.Session()
    tf_function = tf.nn.pool(input=tf_input, window_shape=tf_window_shape, pooling_type=tf_pooling_type, padding=tf_padding, strides=tf_strides)
    tf_output = sess.run(tf_function)
    sess.close()
    
    return tf_output

In [72]:
sample_input = np.random.random([1,4,4,1])
sample_window_shape = [2,2]
sample_pooling_type = "MAX"
sample_padding = "VALID"
sample_strides = [2,2]

tf_output = tf_pooling(sample_input,sample_window_shape,sample_pooling_type,sample_padding,sample_strides)
my_output = my_pooling(sample_input, sample_window_shape, sample_pooling_type, sample_padding, sample_strides)

print("input:")
print(sample_input)
print("output:")
print(tf_output)
print("my output:")
print(my_output)

input:
[[[[0.73587811]
   [0.37249798]
   [0.4192761 ]
   [0.07413942]]

  [[0.54569549]
   [0.67773706]
   [0.35411059]
   [0.73330704]]

  [[0.738413  ]
   [0.52364092]
   [0.59529103]
   [0.47028568]]

  [[0.7114184 ]
   [0.52587802]
   [0.62240085]
   [0.92401336]]]]
output:
[[[[0.73587811]
   [0.73330704]]

  [[0.738413  ]
   [0.92401336]]]]
my output:
[[[[0.]
   [0.]]

  [[0.]
   [0.]]]]
